(function () {
    var games = window.fariusLocalGames || [
        { folder: 'soccer-skills', image: 'soccer-skills.png' },
        { folder: 'deepest-sword', image: 'deepest-sword.jpg' },
        { folder: 'just-fall', image: 'just-fall.jpg' },
        { folder: 'roblox', image: 'roblox.png' },
        { folder: 'HexGL', image: 'hexgl.png' },
        { folder: 'vex6', image: 'vex6.png' },
        { folder: 'fake-virus', image: 'fake-virus.png' },
        { folder: 'dragon-vs-bricks', image: 'dragon-vs-bricks.jpg' },
        { folder: 'sky-car-stunt', image: 'sky-car-stunt.png' },
        { folder: 'champion-island', image: 'champion-island.png' },
        { folder: 'dante', image: 'dante.png' },
        { folder: 'snowrider3d', image: 'snowrider3d.png' },
        { folder: 'adventure-drivers', image: 'adventure-drivers.png' },
        { folder: 'astray', image: 'astray.png' },
        { folder: 'kitchen-gun-game', image: 'kitchen-gun-game.png' },
        { folder: 'slime-rush-td', image: 'slime-rush-td.png' },
        { folder: 'twitch-tetris', image: 'twitch-tetris.png' },
        { folder: 'angry-sharks', image: 'angry-sharks.png' },
        { folder: 'rolling-forests', image: 'rolling-forests.png' },
        { folder: 'cars-simulator', image: 'cars-simulator.png' },
        { folder: 'motox3m-pool', image: 'motox3m-pool.jpg' },
        { folder: 'ns-shaft', image: 'ns-shaft.png' },
        { folder: 'bacon-may-die', image: 'bacon-may-die.png' },
        { folder: 'ctr', image: 'ctr.png' },
        { folder: 'adarkroom', image: 'adarkroom.png' },
        { folder: 'generic-fishing-game', image: 'generic-fishing-game.png' },
        { folder: 'tactical-weapon-pack-2', image: 'tactical-weapon-pack-2.png' },
        { folder: '2048-multitask', image: '2048-multitask.png' },
        { folder: 'duke-nukem-2', image: 'duke-nukem-2.jpg' },
        { folder: 'grindcraft', image: 'grindcraft.png' },
        { folder: 'noob-steve-parkour', image: 'noob-steve-parkour.png' },
        { folder: 'google-feud', image: 'google-feud.png' },
        { folder: 'spelunky', image: 'spelunky.png' },
        { folder: 'sort-the-court', image: 'sort-the-court.png' },
        { folder: 'mindustry', image: 'mindustry.png' },
        { folder: 'volley-random', image: 'volley-random.png' },
        { folder: 'stick-merge', image: 'stick-merge.png' },
        { folder: 'cluster-rush', image: 'cluster-rush.jpg' },
        { folder: '10-minutes-till-dawn', image: '10-minutes-till-dawn.png' },
        { folder: 'webgl-fluid-simulation', image: 'webgl-fluid-simulation.png' },
        { folder: 'DOOMORI', image: 'doomori.png' },
        { folder: 'santy-is-home', image: 'santy-is-home.png' },
        { folder: 'you-are-bezos', image: 'you-are-bezos.png' },
        { folder: 'there-is-no-game', image: 'there-is-no-game.png' },
        { folder: 'rabbit-samurai', image: 'rabbit-samurai.png' },
        { folder: 'gravity-soccer', image: 'gravity-soccer.png' },
        { folder: 'georgeandtheprinter', image: 'georgeandtheprinter.png' },
        { folder: 'mineblocks', image: 'mineblocks.png' },
        { folder: 'gimme-the-airpod', image: 'gimme-the-airpod.png' },
        { folder: 'scratcharia', image: 'scratcharia.png' },
        { folder: 'win-the-whitehouse', image: 'win-the-whitehouse.png' },
        { folder: 'station-141', image: 'station-141.png' },
        { folder: 'merge-round-racers', image: 'merge-round-racers.png' },
        { folder: 'shuttledeck', image: 'shuttledeck.png' },
        { folder: 'hungry-lamu', image: 'hungry-lamu.png' },
        { folder: 'fnaw', image: 'fnaw.png' },
        { folder: 'glass-city', image: 'glass-city.png' },
        { folder: 'froggys-battle', image: 'froggys-battle.png' },
        { folder: 'xx142-b2exe', image: 'xx142-b2exe.png' },
        { folder: 'flappy-bird', image: 'flappy-bird.png' },
        { folder: 'Stickman-Survival', image: 'stickman-survival.png' },
        { folder: 'waterworks', image: 'waterworks.png' },
        { folder: 'roblox copy', image: 'roblox-copy.png' },
        { folder: 'ballistic-chickens', image: 'ballistic-chickens.png' },
        { folder: 'chill-radio', image: 'chill-radio.png' },
        { folder: 'doctor-acorn2', image: 'doctor-acorn2.jpg' },
        { folder: 'snowbattle', image: 'snowbattle.png' },
        { folder: 'sleepingbeauty', image: 'sleepingbeauty.png' },
        { folder: 'slope-ball', image: 'slope-ball.jpg' },
        { folder: 'evolution', image: 'evolution.png' },
        { folder: 'backrooms-2d', image: 'backrooms-2d.png' },
        { folder: 'defend-the-tank', image: 'defend-the-tank.png' },
        { folder: 'protektor', image: 'protektor.jpg' },
        { folder: 'ages-of-conflict', image: 'ages-of-conflict.jpg' },
        { folder: 'ShapeShootout', image: 'shapeshootout.png' },
        { folder: 'precision-client', image: 'precision-client.png' },
        { folder: 'particle-clicker', image: 'particle-clicker.png' },
        { folder: 'factoryballs', image: 'factoryballs.png' },
        { folder: 'om-bounce', image: 'om-bounce.png' },
        { folder: '1v1space', image: '1v1space.png' },
        { folder: 'circlo', image: 'circlo.png' },
        { folder: 'game-inside', image: 'game-inside.png' },
        { folder: 'cubefield', image: 'cubefield.png' },
        { folder: 'ninjavsevilcorp', image: 'ninjavsevilcorp.png' },
        { folder: 'amidst-the-clouds', image: 'amidst-the-clouds.png' },
        { folder: 'the-hotel', image: 'the-hotel.png' },
        { folder: 'tiny-islands', image: 'tiny-islands.png' },
        { folder: 'veloce', image: 'veloce.png' },
        { folder: 'tube-jumpers', image: 'tube-jumpers.jpg' },
        { folder: 'rabbit-samurai2', image: 'rabbit-samurai2.png' },
        { folder: 'jetpack-joyride', image: 'jetpack-joyride.jpg' },
        { folder: 'my-rusty-submarine', image: 'my-rusty-submarine.png' },
        { folder: 'tanuki-sunset', image: 'tanuki-sunset.png' },
        { folder: 'edge-surf', image: 'edge-surf.png' },
        { folder: 'highrisehop', image: 'highrisehop.png' },
        { folder: 'btts', image: 'btts.png' },
        { folder: 'stickman-golf', image: 'stickman-golf.png' },
        { folder: 'aquapark-slides', image: 'aquapark-slides.png' },
        { folder: 'happy-hop', image: 'happy-hop.png' },
        { folder: 'backrooms', image: 'backrooms.png' },
            { folder: 'MonkeyMart', entry: 'index.html', image: 'monkeymart.png' },
            { folder: 'eggycar', entry: 'index.html', image: 'eggycar.png' },
            { folder: 'ltf3', entry: 'index.html', image: 'ltf3.png' },
            { folder: 'drift-boss', entry: 'index.html', image: 'drift-boss.png' },
            { folder: 'pixel-gun-survival', entry: 'index.html', image: 'pixel-gun-survival.jpg' },
            { folder: 'Rocket-League', entry: 'index.html', image: 'rocket-league.png' },
            { folder: 'smashkarts', entry: 'index.html', image: 'smashkarts.png' },
            { folder: 'fruitninja', entry: 'index.html', image: 'fruitninja.png' },
            { folder: 'soccer-random', entry: 'index.html', image: 'soccer-random.png' },
            { folder: 'superhot', entry: 'index.html', image: 'superhot.jpg' },
            { folder: 'chrome-dino', entry: 'index.html', image: 'chrome-dino.png' },
            { folder: 'tacticalassasin2', entry: 'index.html', image: 'tacticalassasin2.png' },
            { folder: 'ducklife3', entry: 'index.html', image: 'ducklife3.png' },
            { folder: 'adrenalinechallenge', entry: 'index.html', image: 'adrenalinechallenge.jpg' },
            { folder: 'subway-surfers-ny', entry: 'index.html', image: 'subway-surfers-ny.png' },
            { folder: 'ducklife2', entry: 'index.html', image: 'ducklife2.png' },
            { folder: 'madalin-stunt-cars-2', entry: 'index.html', image: 'madalin-stunt-cars-2.jpg' },
            { folder: 'worlds-hardest-game', entry: 'index.html', image: 'worlds-hardest-game.png' },
            { folder: 'hexempire', entry: 'index.html', image: 'hexempire.jpg' },
            { folder: 'monster-tracks', entry: 'index.html', image: 'monster-tracks.jpg' },
            { folder: 'blackknight', entry: 'index.html', image: 'blackknight.png' },
            { folder: 'theheist', entry: 'index.html', image: 'theheist.jpg' },
            { folder: 'soldier-legend', entry: 'index.html', image: 'soldier-legend.png' },
            { folder: 'btd5', entry: 'index.html', image: 'btd5.png' },
            { folder: 'invite-the-blackbird', entry: 'index.html', image: 'invite-the-blackbird.png' },
            { folder: 'google-snake', entry: 'index.html', image: 'google-snake.png' },
            { folder: 'riddleschool', entry: 'index.html', image: 'riddleschool.png' },
            { folder: 'run4bootleg', entry: 'index.html', image: 'run4bootleg.png' },
            { folder: 'drift-hunters', entry: 'index.html', image: 'drift-hunters.png' },
            { folder: 'motox3m2', entry: 'index.html', image: 'motox3m2.png' },
            { folder: 'ctr-holiday', entry: 'index.html', image: 'ctr-holiday.png' },
            { folder: 'level13', entry: 'index.html', image: 'level13.png' },
            { folder: 'learntofly2', entry: 'index.html', image: 'learntofly2.jpg' },
            { folder: 'swerve', entry: 'index.html', image: 'swerve.jpg' },
            { folder: 'iceagebaby2', entry: 'index.html', image: 'iceagebaby2.png' },
            { folder: 'bloonstd', entry: 'index.html', image: 'bloonstd.jpg' },
            { folder: 'spacegarden', entry: 'index.html', image: 'spacegarden.png' },
            { folder: 'slope', entry: 'index.html', image: 'slope.jpeg' },
            { folder: 'shotinthedark', entry: 'index.html', image: 'shotinthedark.png' },
            { folder: 'deal-or-no-deal', entry: 'index.html', image: 'deal-or-no-deal.jpg' },
            { folder: 'bigredbutton', entry: 'index.html', image: 'bigredbutton.png' },
            { folder: 'cnpingpong', entry: 'index.html', image: 'cnpingpong.png' },
            { folder: 'doge2048', entry: 'index.html', image: 'doge2048.png' },
            { folder: 'earntodie', entry: 'index.html', image: 'earntodie.png' },
            { folder: 'soundboard', entry: 'index.html', image: 'soundboard.jpeg' },
            { folder: 'stormthehouse2', entry: 'index.html', image: 'stormthehouse2.jpg' },
            { folder: 'madalin-stunt-cars-3', entry: 'index.html', image: 'madalin-stunt-cars-3.png' },
            { folder: 'space-company', entry: 'index.html', image: 'space-company.png' },
            { folder: 'wolf3d', entry: 'index.html', image: 'wolf3d.png' },
            { folder: 'legacyflashgames', entry: 'sesame/games/abbys-sandbox-search/index.html', image: 'legacyflashgames.png' },
            { folder: 'thebattle', entry: 'index.html', image: 'thebattle.png' },
            { folder: 'planetlife', entry: 'index.html', image: 'planetlife.png' },
            { folder: 'craftmine', entry: 'index.html', image: 'craftmine.png' },
            { folder: 'helicopter', entry: 'index.html', image: 'helicopter.png' },
            { folder: 'vex4', entry: 'index.html', image: 'vex4.png' },
            { folder: 'shellshockers', entry: 'index.html', image: 'shellshockers.png' },
            { folder: 'gearsofbabies', entry: 'index.html', image: 'gearsofbabies.png' },
            { folder: 'sand-game', entry: 'index.html', image: 'sand-game.PNG' },
            { folder: 'impossiblequiz', entry: 'index.html', image: 'impossiblequiz.png' },
            { folder: 'iceagebaby', entry: 'index.html', image: 'iceagebaby.png' },
            { folder: 'escapingtheprison', entry: 'index.html', image: 'escapingtheprison.jpg' },
            { folder: 'bad-ice-cream', entry: 'index.html', image: 'bad-ice-cream.jpg' },
            { folder: 'exo', entry: 'index.html', image: 'exo.jpg' },
            { folder: 'minesweeper', entry: 'beginner/index.html', image: 'minesweeper.png' },
            { folder: 'learntofly', entry: 'index.html', image: 'learntofly.png' },
            { folder: 'smokingbarrels', entry: 'index.html', image: 'smokingbarrels.jpg' },
            { folder: 'knife-master', entry: 'index.html', image: 'knife-master.jpg' },
            { folder: 'connect3', entry: 'index.html', image: 'connect3.png' },
            { folder: 'kittencannon', entry: 'index.html', image: 'kittencannon.png' },
            { folder: 'a-dance-of-fire-and-ice', entry: 'index.html', image: 'a-dance-of-fire-and-ice.png' },
            { folder: 'roommate', entry: '31/index.html', image: 'roommate.png' },
            { folder: 'stealingthediamond', entry: 'index.html', image: 'stealingthediamond.jpg' },
            { folder: 'webxash', entry: 'index.html', image: 'webxash.png' },
            { folder: 'cupcake2048', entry: 'index.html', image: 'cupcake2048.png' },
            { folder: 'endlesswar3', entry: 'index.html', image: 'endlesswar3.png' },
            { folder: 'tiny-fishing', entry: 'index.html', image: 'tiny-fishing.png' },
            { folder: 'riddletransfer', entry: 'index.html', image: 'riddletransfer.png' },
            { folder: 'Run 2', entry: 'index.html', image: 'run-2.jpg' },
            { folder: 'DogeMiner', entry: 'index.html', image: 'dogeminer.png' },
            { folder: 'just-one-boss', entry: 'index.html', image: 'just-one-boss.png' },
            { folder: 'papaspizzaria', entry: 'index.html', image: 'papaspizzaria.jpg' },
            { folder: 'rolly-vortex', entry: 'index.html', image: 'rolly-vortex.png' },
            { folder: 'meme2048', entry: 'index.html', image: 'meme2048.png' },
            { folder: 'tosstheturtle', entry: 'index.html', image: 'tosstheturtle.png' },
            { folder: 'idle-shark', entry: 'index.html', image: 'idle-shark.png' },
            { folder: 'stationmeltdown', entry: 'Build/index.html', image: 'stationmeltdown.png' },
            { folder: 'canyondefense', entry: 'index.html', image: 'canyondefense.png' },
            { folder: 'bloxors', entry: 'index.html', image: 'bloxors.png' },
            { folder: 'n-gon', entry: 'index.html', image: 'n-gon.png' },
            { folder: 'osu!', entry: 'index.html', image: 'osu.png' },
            { folder: 'hardware-tycoon', entry: 'index.html', image: 'hardware-tycoon.png' },
            { folder: 'riddleschool4', entry: 'index.html', image: 'riddleschool4.png' },
            { folder: 'go-ball', entry: 'index.html', image: 'go-ball.png' },
            { folder: 'awesometanks2', entry: 'index.html', image: 'awesometanks2.jpg' },
            { folder: 'solitaire', entry: 'index.html', image: 'solitaire.png' },
            { folder: 'push-your-luck', entry: 'index.html', image: 'push-your-luck.png' },
            { folder: 'stickman-hook', entry: 'index.html', image: 'stickman-hook.jpg' },
            { folder: 'krunker', entry: 'index.html', image: 'krunker.png' },
            { folder: 'riddleschool3', entry: 'index.html', image: 'riddleschool3.png' },
            { folder: 'nsresurgence', entry: 'index.html', image: 'nsresurgence.png' },
        { folder: 'minecraft-classic', entry: 'index.html', image: 'minecraft-classic.png' },
        { folder: 'worlds-hardest-game-2', entry: 'index.html', image: 'worlds-hardest-game-2.jpg' },
        { folder: 'bad-ice-cream-3', entry: 'index.html', image: 'bad-ice-cream-3.jpg' },
        { folder: 'doublewires', entry: 'index.html', image: 'doublewires.png' },
        { folder: 'rooftop-snipers', entry: 'index.html', image: 'rooftop-snipers.png' },
        { folder: 'btd4', entry: 'index.html', image: 'btd4.jpg' },
        { folder: 'Dogeminer2', entry: 'index.html', image: 'dogeminer2.jpg' },
        { folder: 'bad-ice-cream-2', entry: 'index.html', image: 'bad-ice-cream-2.jpg' },
        { folder: 'eaglerfaithful', entry: 'index.html', image: 'eaglerfaithful.png' },
        { folder: 'marvinspectrum', entry: 'index.html', image: 'marvinspectrum.png' },
        { folder: 'spinningrat', entry: 'index.html', image: 'spinningrat.jpg' },
        { folder: 'webretro', entry: 'info/index.html', image: 'webretro.png' },
        { folder: 'hba', entry: 'index.html', image: 'hba.JPG' },
        { folder: 'bus and subway', entry: 'index.html', image: 'bus-and-subway.png' },
        { folder: 'angelunder', entry: 'index.html', image: 'angelunder.png' },
        { folder: 'riddletransfer2', entry: 'index.html', image: 'riddletransfer2.png' },
        { folder: 'creativekillchamber', entry: 'index.html', image: 'creativekillchamber.jpg' },
        { folder: 'greybox', entry: 'index.html', image: 'greybox.png' },
        { folder: 'superfowlist', entry: 'index.html', image: 'superfowlist.png' },
        { folder: 'flappy-2048', entry: 'index.html', image: 'flappy-2048.png' },
        { folder: 'Trimps', entry: 'index.html', image: 'trimps.png' },
        { folder: 'throwrocks', entry: 'index.html', image: 'throwrocks.png' },
        { folder: 'weavesilk', entry: 'index.html', image: 'weavesilk.png' },
        { folder: 'bloonstd2', entry: 'index.html', image: 'bloonstd2.png' },
        { folder: 'webcleaner', entry: 'index.html', image: 'webcleaner.png' },
        { folder: 'sushi-unroll', entry: 'index.html', image: 'sushi-unroll.png' },
        { folder: 'amazing-rope-police', entry: 'index.html', image: 'amazing-rope-police.jpeg' },
        { folder: 'missiles', entry: 'index.html', image: 'missiles.png' },
        { folder: 'geodash', entry: 'index.html', image: 'geodash.png' },
        { folder: 'yoshifabrication', entry: 'index.html', image: 'yoshifabrication.png' },
        { folder: 'scooperia', entry: 'index.html', image: 'scooperia.png' },
        { folder: 'fireboywatergirlforesttemple', entry: 'index.html', image: 'fireboywatergirlforesttemple.png' },
        { folder: 'evil-glitch', entry: 'index.html', image: 'evil-glitch.png' },
        { folder: 'basketball-stars', entry: 'index.html', image: 'basketball-stars.png' },
        { folder: 'alienhominid', entry: 'index.html', image: 'alienhominid.jpg' },
        { folder: 'minecraft-15', entry: 'index.html', image: 'minecraft-15.png' },
        { folder: 'edgenotfound', entry: 'index.html', image: 'edgenotfound.png' },
        { folder: 'hextris', entry: 'index.html', image: 'hextris.png' },
        { folder: 'stick-duel-battle', entry: 'index.html', image: 'stick-duel-battle.jpg' },
        { folder: 'motox3m-winter', entry: 'index.html', image: 'motox3m-winter.png' },
        { folder: 'yohoho', entry: 'index.html', image: 'yohoho.png' },
        { folder: 'crossyroad', entry: 'index.html', image: 'crossyroad.png' },
        { folder: 'townscaper', entry: 'index.html', image: 'townscaper.jpg' },
        { folder: 'temple-run-2', entry: 'index.html', image: 'temple-run-2.webp' },
        { folder: 'tunnel-rush', entry: 'index.html', image: 'tunnel-rush.png' },
        { folder: 'stickman-boost', entry: 'index.html', image: 'stickman-boost.jpeg' },
        { folder: 'fairsquares', entry: 'index.html', image: 'fairsquares.png' },
        { folder: 'boxhead2play', entry: 'index.html', image: 'boxhead2play.jpg' },
        { folder: 'minecraftbeta', entry: 'index.html', image: 'minecraftbeta.png' },
        { folder: 'interactivebuddy', entry: 'index.html', image: 'interactivebuddy.jpg' },
        { folder: 'align-4', entry: 'index.html', image: 'align-4.png' },
        { folder: 'stickwar', entry: 'index.html', image: 'stickwar.jpg' },
        { folder: 'ssurferbotleg', entry: 'index.html', image: 'ssurferbotleg.png' },
        { folder: 'starve', entry: 'index.html', image: 'starve.png' },
        { folder: 'miniputt', entry: 'index.html', image: 'miniputt.png' },
        { folder: 'boxing-random', entry: 'index.html', image: 'boxing-random.jpg' },
        { folder: 'championarcher', entry: 'index.html', image: 'championarcher.png' },
        { folder: 'thisistheonlylevel', entry: 'index.html', image: 'thisistheonlylevel.png' },
        { folder: 'hellscaper', entry: 'Hellscaper WebGL 4-19-23/index.html', image: 'hellscaper.png' },
        { folder: 'idledices', entry: 'index.html', image: 'idledices.png' },
        { folder: 'avalanche', entry: 'index.html', image: 'avalanche.png' },
        { folder: '99balls', entry: 'index.html', image: '99balls.png' },
        { folder: 'breakingthebank', entry: 'index.html', image: 'breakingthebank.png' },
        { folder: 'poom', entry: 'index.html', image: 'poom.png' },
        { folder: 'wounded-summer-baby-edition', entry: 'index.html', image: 'wounded-summer-baby-edition.png' },
        { folder: 'vex3', entry: 'index.html', image: 'vex3.png' },
        { folder: 'happywheels', entry: 'index.html', image: 'happywheels.png' },
        { folder: 'runner', entry: 'index.html', image: 'runner.png' },
        { folder: 'zombs-royale', entry: 'index.html', image: 'zombs-royale.png' },
        { folder: 'hackertype', entry: 'index.html', image: 'hackertype.png' },
        { folder: 'surviv', entry: 'index.html', image: 'surviv.png' },
        { folder: 'battleforgondor', entry: 'index.html', image: 'battleforgondor.JPG' },
        { folder: 'elasticman', entry: 'index.html', image: 'elasticman.jpg' },
        { folder: 'popcat-classic', entry: 'index.html', image: 'popcat-classic.png' },
        { folder: 'motox3m-spooky', entry: 'index.html', image: 'motox3m-spooky.jpeg' },
        { folder: 'ninja', entry: 'index.html', image: 'ninja.png' },
        { folder: 'blockpost', entry: 'index.html', image: 'blockpost.jpg' },
        { folder: '9007199254740992', entry: 'index.html', image: '9007199254740992.png' },
        { folder: 'fridaynightfunkin', entry: 'index.html', image: 'fridaynightfunkin.png' },
        { folder: 'wolf2d', entry: 'index.html', image: 'wolf2d.png' },
        { folder: 'ducklife4', entry: 'index.html', image: 'ducklife4.jpg' },
        { folder: 'fleeingthecomplex', entry: 'index.html', image: 'fleeingthecomplex.png' },
        { folder: 'draw-the-hill', entry: 'index.html', image: 'draw-the-hill.png' },
        { folder: 'tv-static', entry: 'index.html', image: 'tv-static.png' },
        { folder: 'OfflineParadise', entry: 'index.html', image: 'offlineparadise.jpeg' },
        { folder: 'riddleschool5', entry: 'index.html', image: 'riddleschool5.png' },
        { folder: 'gachalife', entry: 'index.html', image: 'gachalife.webp' },
        { folder: 'doodle-jump', entry: 'index.html', image: 'doodle-jump.png' },
        { folder: 'vex7', entry: 'index.html', image: 'vex7.png' },
        { folder: 'ctr-tr', entry: 'index.html', image: 'ctr-tr.png' },
        { folder: 'push-the-square', entry: 'index.html', image: 'push-the-square.png' },
        { folder: 'the-final-earth-2', entry: 'index.html', image: 'the-final-earth-2.png' },
        { folder: 'riddleschool2', entry: 'index.html', image: 'riddleschool2.png' },
        { folder: 'flappybird', entry: 'index.html', image: 'flappybird.png' },
        { folder: 'wordle', entry: 'index.html', image: 'wordle.png' },
        { folder: 'resent-client', entry: '1.8/index.html', image: 'resent-client.png' },
        { folder: 'cell-machine', entry: 'index.html', image: 'cell-machine.png' },
        { folder: 'bntts', entry: 'index.html', image: 'bntts.png' },
        { folder: 'core-ball', entry: 'index.html', image: 'core-ball.png' }
    ];

    function displayName(folder) {
        return folder.replace(/[-_]+/g, ' ').replace(/\b\w/g, function (letter) {
            return letter.toUpperCase();
        });
    }

    var grid = document.getElementById('gameGallery');
    if (!grid) return;

    while (grid.children.length > 1) {
        grid.removeChild(grid.lastElementChild);
    }

    games.forEach(function (game, index) {
        var card = document.createElement('a');
        card.className = 'gl-card';
        card.href = 'games/' + encodeURIComponent(game.folder) + '/' + (game.entry || '');
        card.style.setProperty('--i', grid.children.length + index);

        var art = document.createElement('span');
        art.className = 'gl-art';

        var image = document.createElement('img');
        var folderPath = 'games/' + encodeURIComponent(game.folder) + '/';
        var imageSources = [
            folderPath + 'splash.png',
            folderPath + 'splash.jpg',
            folderPath + 'icon.png'
        ];
        var logoPath = window.fariusGameLogos && window.fariusGameLogos[game.folder];
        if (logoPath) {
            imageSources.push(folderPath + logoPath.split('/').map(encodeURIComponent).join('/'));
        }
        if (game.image) imageSources.push('images/' + game.image);
        imageSources.push('png/gamepad-solid.svg');

        var imageIndex = 0;
        image.onerror = function () {
            imageIndex++;
            if (imageIndex < imageSources.length) image.src = imageSources[imageIndex];
        };
        image.src = imageSources[imageIndex];
        image.alt = '';
        image.loading = 'lazy';
        image.decoding = 'async';

        var play = document.createElement('span');
        play.className = 'gl-play';
        play.textContent = 'Play';

        var title = document.createElement('h3');
        title.textContent = displayName(game.folder);

        art.appendChild(image);
        art.appendChild(play);
        card.appendChild(art);
        card.appendChild(title);
        grid.appendChild(card);
    });
})();
